In [3]:
import numpy as np

In [4]:
zeros = np.zeros(10)

In [5]:
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
full = np.full(10, 0.0)

In [7]:
print(full)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
array = np.repeat([0.0, 1.0], 5)

In [9]:
print(array)

[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]


In [14]:
array1 = np.repeat([0.0, 1.0],[5,10])

In [15]:
array1

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
its_a_list = [1,2,3,4]

In [17]:
array = np.array(its_a_list)

In [19]:
array

array([1, 2, 3, 4])

In [20]:
array = [[1,2,3],[4,5,6],[7,8,9]]

In [21]:
array1 = np.array(array)

In [22]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array1[2, 2]

9

In [34]:
array1.shape

(3, 3)

In [41]:
numbers = np.arange(1, 10)

In [42]:
numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
result = array1 ** 2

In [44]:
result

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [45]:
result2 = array1 * result

In [46]:
result2

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [47]:
mat = np.arange(15).reshape(5,3)

In [48]:
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [49]:
mat.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
vec1 = np.arange(10)

In [51]:
vec1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
vec2 = np.arange(10,20)

In [53]:
vec2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
vec1.dot(vec2)

735

In [55]:
vec1.dot(vec1)

285

In [56]:
1 ** 2 + 2 ** 2 + 3 ** 2 + 4 ** 2 + 5 ** 2 + 6 ** 2 + 7 ** 2 + 8 ** 2 + 9 ** 2

285

In [10]:
vec3 = np.arange(5).reshape(5,1)

In [58]:
vec3

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [21]:
vec4 = np.arange(1, 6).reshape(1,5)

In [22]:
vec4

array([[1, 2, 3, 4, 5]])

In [29]:
vec3.dot(vec4)

array([[ 0,  0,  0,  0,  0],
       [ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20]])

In [26]:
vec1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
vec1 / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [28]:
vec3 * vec4

array([[ 0,  0,  0,  0,  0],
       [ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20]])

In [30]:
vec1.dot(vec1)

285

In [32]:
vec1.shape

(10,)